# ==============================================
# FAMACHAT - DOCKER COMPOSE STANDALONE
# ==============================================
version: '3.8'

services:
  # ==============================================
  # POSTGRESQL DATABASE
  # ==============================================
  postgres:
    image: postgres:16-alpine
    container_name: famachat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: famachat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD:-IwOLgVnyOfbN}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - network_public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d famachat"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # ==============================================
  # REDIS CACHE & SESSIONS
  # ==============================================
  redis:
    image: redis:7-alpine
    container_name: famachat-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - network_public
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # ==============================================
  # FAMACHAT APPLICATION
  # ==============================================
  famachat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: famachat-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Application
      NODE_ENV: production
      PORT: 5000
      APP_URL: ${APP_URL:-https://famachat.seudominio.com}
      
      # Database
      DATABASE_URL: postgresql://postgres:${PGPASSWORD:-IwOLgVnyOfbN}@postgres:5432/famachat
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: famachat
      PGUSER: postgres
      PGPASSWORD: ${PGPASSWORD:-IwOLgVnyOfbN}
      
      # Redis
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      
      # Security
      SESSION_SECRET: ${SESSION_SECRET:-EuCIxyXv8hgm64fhG2U8ytC3NoH59jsPxWaqwYFttMJI0mSNlSG1W73jbh2zu4+yUHLPecyaC5UMikeWz2B8qw==}
      JWT_SECRET: ${JWT_SECRET:-FamaChat2024SecretKeyForJWTTokenGeneration123456789}
      
      # APIs
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-https://evolution.famachat.com.br}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-IwOLgVnyOfbN}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_api_key}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-AIzaSyAzqIdg1EKaI8cmb2W4iC6NfJs_D8vgEYY}
      
      # Facebook
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID:-1600246764019855}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET:-1600246764019855}
      FACEBOOK_PAGE_TOKEN: ${FACEBOOK_PAGE_TOKEN:-711015865662935}
      
      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      
      # Upload Limits
      REQUEST_SIZE_LIMIT: 50mb
      URL_ENCODED_LIMIT: 50mb
      JSON_LIMIT: 10mb
      
    volumes:
      - uploads_data:/app/server/uploads
      - logs_data:/app/logs
    ports:
      - "5000:5000"
    networks:
      - network_public
    labels:
      # Traefik Configuration
      - "traefik.enable=true"
      - "traefik.docker.network=network_public"
      
      # HTTP Router
      - "traefik.http.routers.famachat.rule=Host(`${DOMAIN:-famachat.seudominio.com}`)"
      - "traefik.http.routers.famachat.entrypoints=websecure"
      - "traefik.http.routers.famachat.tls.certresolver=letsencrypt"
      
      # Service
      - "traefik.http.services.famachat.loadbalancer.server.port=5000"
      
      # Middleware
      - "traefik.http.routers.famachat.middlewares=famachat-headers"
      - "traefik.http.middlewares.famachat-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.famachat-headers.headers.customrequestheaders.X-Forwarded-For="
      
      # HTTP to HTTPS Redirect
      - "traefik.http.routers.famachat-http.rule=Host(`${DOMAIN:-famachat.seudominio.com}`)"
      - "traefik.http.routers.famachat-http.entrypoints=web"
      - "traefik.http.routers.famachat-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/system/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # ==============================================
  # BACKUP SERVICE (OPCIONAL)
  # ==============================================
  backup:
    image: postgres:16-alpine
    container_name: famachat-backup
    restart: "no"
    depends_on:
      - postgres
    environment:
      PGPASSWORD: ${PGPASSWORD:-IwOLgVnyOfbN}
    volumes:
      - backup_data:/backup
      - ./scripts/backup.sh:/backup.sh:ro
    networks:
      - network_public
    command: >
      sh -c "
        while ! pg_isready -h postgres -U postgres; do
          echo 'Aguardando PostgreSQL...'
          sleep 2
        done
        echo 'PostgreSQL pronto - executando backup'
        pg_dump -h postgres -U postgres -d famachat > /backup/famachat_backup_$$(date +%Y%m%d_%H%M%S).sql
        echo 'Backup concluído'
      "
    profiles:
      - backup

# ==============================================
# NETWORKS
# ==============================================
networks:
  network_public:
    name: network_public
    external: true

# ==============================================
# VOLUMES
# ==============================================
volumes:
  postgres_data:
    driver: local
    name: famachat_postgres_data
  redis_data:
    driver: local
    name: famachat_redis_data
  uploads_data:
    driver: local
    name: famachat_uploads_data
  logs_data:
    driver: local
    name: famachat_logs_data
  backup_data:
    driver: local
    name: famachat_backup_data