# ==============================================
# FAMACHAT - DOCKER SWARM (FIXED)
# ==============================================
version: '3.8'

services:
  # ==============================================
  # POSTGRESQL DATABASE
  # ==============================================
  postgres:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == manager
    environment:
      POSTGRES_DB: famachat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD:-IwOLgVnyOfbN}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d famachat"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ==============================================
  # REDIS CACHE & SESSIONS
  # ==============================================
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ==============================================
  # FAMACHAT APPLICATION
  # ==============================================
  famachat:
    image: ${REGISTRY:-famachat}:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.famachat.rule=Host(`${DOMAIN:-famachat.seudominio.com}`)"
        - "traefik.http.routers.famachat.entrypoints=websecure"
        - "traefik.http.routers.famachat.tls.certresolver=letsencrypt"
        - "traefik.http.services.famachat.loadbalancer.server.port=5000"
        - "traefik.http.routers.famachat.middlewares=famachat-headers"
        - "traefik.http.middlewares.famachat-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.famachat-http.rule=Host(`${DOMAIN:-famachat.seudominio.com}`)"
        - "traefik.http.routers.famachat-http.entrypoints=web"
        - "traefik.http.routers.famachat-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      NODE_ENV: production
      PORT: 5000
      APP_URL: https://${DOMAIN:-famachat.seudominio.com}
      DATABASE_URL: postgresql://postgres:${PGPASSWORD:-IwOLgVnyOfbN}@postgres:5432/famachat
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: famachat
      PGUSER: postgres
      PGPASSWORD: ${PGPASSWORD:-IwOLgVnyOfbN}
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      SESSION_SECRET: ${SESSION_SECRET:-EuCIxyXv8hgm64fhG2U8ytC3NoH59jsPxWaqwYFttMJI0mSNlSG1W73jbh2zu4+yUHLPecyaC5UMikeWz2B8qw==}
      JWT_SECRET: ${JWT_SECRET:-FamaChat2024SecretKeyForJWTTokenGeneration123456789}
      EVOLUTION_API_URL: ${EVOLUTION_API_URL:-https://evolution.famachat.com.br}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY:-IwOLgVnyOfbN}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-your_openai_api_key}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-AIzaSyAzqIdg1EKaI8cmb2W4iC6NfJs_D8vgEYY}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID:-1600246764019855}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET:-1600246764019855}
      FACEBOOK_PAGE_TOKEN: ${FACEBOOK_PAGE_TOKEN:-711015865662935}
    volumes:
      - uploads_data:/app/server/uploads
      - logs_data:/app/logs
    networks:
      - backend
      - network_public
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/system/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# ==============================================
# NETWORKS
# ==============================================
networks:
  backend:
    driver: overlay
    attachable: true
  network_public:
    external: true

# ==============================================
# VOLUMES
# ==============================================
volumes:
  postgres_data:
  redis_data:
  uploads_data:
  logs_data: